### ISSUE TITLE
`neovim.api.nvim.NvimError: b'Vim(let):E121: Undefined variable: b:compl_context'`

### ISSUE THREAD

**Issue by dbellavista** [carlitux/deoplete-ternjs#44]
```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/daniele/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/source/omni.py", line 99, in gather_candidates
[deoplete]   File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 131, in request
[deoplete]     self.__omnifunc, 0, context['complete_str'])
[deoplete]     res = self._session.request(name, *args, **kwargs)
[deoplete]   File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 230, in call
[deoplete]   File "/usr/local/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
[deoplete]     return self.request('nvim_call_function', name, args, **kwargs)
[deoplete]     raise self.error_wrapper(err)
[deoplete] neovim.api.nvim.NvimError: b'Vim(let):E121: Undefined variable: b:compl_context'
[deoplete] neovim.api.nvim.NvimError: b'Vim(let):E121: Undefined variable: b:compl_context'
[deoplete] neovim.api.nvim.NvimError: b'Vim(let):E121: Undefined variable: b:compl_context'
[deoplete] Error occurred calling omnifunction: javascriptcomplete#CompleteJS.  Use :messages for error details.
```

**Comment by carlitux** [comment]
@dbellavista this happens at deoplete on vimscript code. Please report there.
