### ISSUE TITLE
KeyError 'is_async'

### ISSUE THREAD

**Issue by charlieblevins** [carlitux/deoplete-ternjs#73]
Thanks for the awesome plugin.

When typing javascript in a javascript file in neovim I get the following error messages:
```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/cblevins/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 110, in gather_results
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/Users/cblevins/.vim/plugged/deoplete-ternjs/rplugin/python3/deoplete/sources/ternjs.py", line 94, in gather_candidates
[deoplete]     if context['is_async']:
[deoplete] KeyError: 'is_async'
[deoplete] Could not get completions from: tern.  Use :messages for error details.
```

I'm unfamiliar with python, but I'm assuming this means I have a misconfiguration that causes `context` to be missing this is_async key. What are some possible causes for this error?

As background I'm using:
Neovim
tern_for_vim
deoplete-ternjs

I do have the following in my .vimrc:
```
" Deoplete-TERN
" Use tern_for_vim.
let g:tern#command = ["tern"]
let g:tern#arguments = ["--persistent"]
```

**Comment by carlitux** [comment]
@charlieblevins please check you have latest versions of deoplete and deoplete-ternjs. Also python-neovim.

**Comment by charlieblevins** [comment]
Updating deoplete solved it. Thanks!
