### ISSUE TITLE
Error when i try to open js file

### ISSUE THREAD

**Issue by Skrip42** [carlitux/deoplete-ternjs#87]
When i try to open js file, i get error:
`
[deoplete] Traceback (most recent call last):
File "/home/skrip/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/child.py", line 448, in _itersource
    source.on_init(context)
  File "/home/skrip/.vim/bundle/deoplete-ternjs/rplugin/python3/deoplete/sources/ternjs.py", line 45, in on_init
   self._tern_depths = bool(vars.get('deoplete#sources#ternjs#depths', 0))
  File "/home/skrip/.local/lib/python3.7/site-packages/pynvim/api/common.py", line 138, in get
   return self.__getitem__(key)
  File "/home/skrip/.local/lib/python3.7/site-packages/pynvim/api/common.py", line 110, in __getitem__
    raise transform_keyerror(exc)
  File "/home/skrip/.local/lib/python3.7/site-packages/pynvim/api/common.py", line 108, in __getitem__
    return self._get(key)
  File "/home/skrip/.local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/skrip/.local/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: 'deoplete#sources#ternjs#depths'
Error when loading source tern: 'deoplete#sources#ternjs#depths'. Ignoring..  Use :messages / see above for error details.
`
and completion does not work.
Maybe I'm doing something wrong?
Other deoplete extensions work correctly....

**Comment by carlitux** [comment]
Which version are you using?

do you have a minimal config to reproduce?

**Comment by Skrip42** [comment]
i use actual master of deoplete-ternjs
and tern version 0.24.2

my .tern-project:
`{
    "libs": [
        "ecma5",
        "browser",
        "jquery"
    ],
    "loadEnerly": [],
    "async": true,
    "dontLoad": [
        "node_modules",
        "vendor",
        "public"
    ],
    "exclude": [
        "node_modules/**",
        ".git/**",
        "vendor",
        "public/**"
    ],
    "plugins": {
        "doc_comment": {
            "fullDocs": true
        },
        "complete_strings": {},
        "es_modules": {},
        "modules": {},
        "node": {},
        "commonjs": {},
        "node_resolve":{}
    }
}
`
and my .vimrc:
`
...................
let g:deoplete#enable_at_startup = 1

let g:deoplete#sources#ternjs#tern_bin = '/usr/local/bin/tern'
let g:deoplete#sources#ternjs#timeout = 1
..............
`
I also tried default configs, with the same result

**Comment by carlitux** [comment]
Vim/Neovim version?

**Comment by Skrip42** [comment]
vim 8.1.2231

**Comment by carlitux** [comment]
please update and let me know if now works

**Comment by Skrip42** [comment]
Yes, now everything works correctly! Many thanks!
